### ISSUE TITLE
email

### ISSUE THREAD

**Issue by joshp23** [YOURLS/custom-protocol#1]
This may be a dumb question, but would this work to mask email addresses by merely adding `mailto:` or would the `@` break things?

**Comment by ozh** [comment]
Not sure I understand. Out of the box, `mailto:` works, eg http://yourls.org/email

**Comment by joshp23** [comment]
Wow, I don't know how I missed that... excuse me while I go RTFD...

**Comment by ozh** [comment]
Feel free to point out any lacking info in said FD :)
